# Generated by Django 4.0.2 on 2022-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
