# Generated by Django 4.0.2 on 2022-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=400),
        ),
    ]
